repository:
  name: different
  description: "Pretty line-based diff printouts (bin and library)"
  homepage: "https://github.com/adam-gaia/different"
  topics:
    - TODO
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: main
  allow_merge_commit: true
  allow_squash_merge: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
branches:
  - name: main
    protection:
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: false
      required_pull_request_reviews: null
      restrictions: null
