repository:
  name: different
  description: "Pretty line-based diff printouts (bin and library)"
  homepage: "https://github.com/adam-gaia/different"
  topics:
    - TODO
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_merge_commit: true
  allow_squash_merge: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_vulnerability_alerts: true
  enable_automated_security_fixes: true
branches:
  - name: main
    protection:
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
        dismiss_stale_reviews: false
      required_linear_history: true
      restrictions: null
